### ISSUE TITLE
realms

### ISSUE THREAD

**Issue by bnlawrence** [NCAS-CMS/canari-data#18]
We have agreed we need the realms, for the ocean and sea ice that should be ok, but for the atmosphere we either have to 
split the land off into their own files, or do per variable realms. The former is preferred (and can be done via stash table).

**Comment by grenville** [comment]
Not so simple as originally thought - we'll need to identify individual stash items for Land and LandIce (they're not separated in stash sections)

Is there a list of standard names associated with a realm?

**Comment by bnlawrence** [comment]
I am pretty skeptical too, because there is also the aerosol realm. I suspect it's simply not necessary for a SMLE.

**Comment by davidhassell** [comment]
> a field can be in more than one realm eg, mole_fraction_of_ozone_in_air is in atmos, atmosChem, aerosol (if I understood the CMIP6_MIP_tables.xlsx correclty)

That's how I understand it, too, Grenville, looking at, e.g. one of the tabs in https://clipc-services.ceda.ac.uk/dreq/data/tabs02/cmvmm_CMIP_ScenarioMIP_3_3.xlsx

I wouldn't be surprised if there are cases in CMIP6 where the same variable has a different realm depending on the context of its data request table (but I don't have any evidence for this!)

Given that the realm(s) would be stored as attributes on individual variables (right?) - how would these be actually used after the models have finished running?

**Comment by bnlawrence** [comment]
Agreed to keep our three realms as is.
