### ISSUE TITLE
Make sure instantaneous fields do not have spurious time means

### ISSUE THREAD

**Issue by bnlawrence** [NCAS-CMS/canari-data#2]
A large number of fields which are instantaneous fields at a specific time have spurious cell methods. E.g. 
```
Field: surface_temperature (ncvar%m01s00i507_10)
------------------------------------------------
Data            : surface_temperature(time(241), latitude(324), longitude(432)) K
Cell methods    : time(241): mean (interval: 900 s)
Dimension coords: latitude(324) = [-89.72222137451172, ..., 89.72222137451172] degrees_north
                : longitude(432) = [0.4166666567325592, ..., 359.5833435058594] degrees_east
Auxiliary coords: time(time(241)) = [1950-01-01 01:30:00, ..., 1950-01-30 22:30:00] 360_day
```
is either supposed to be hourly instantaneous data, no cell method, or it's hourly averages, it's not this!

**Comment by bnlawrence** [comment]
These are supposed to be hourly means. Is Bryan misinterpreting the meaning of the interval?

**Comment by bnlawrence** [comment]
Ok, I had thought these were instantaneous fields, and they are not. They are one hour averages of data sampled every 900s (the timestep). It would appear that the only way we know that these are hourly averages by inspecting the time bounds, or the variable attributes:
```
m01s04i203:interval_operation = "900 s" ;
m01s04i203:interval_write = "1 h" ;
```
Right now I am not sure where the controlled vocabulary comes from for these attributes.

It's certainly the case that it would be helpful if the cf-python print summary were to expose the time-averaging period.

**Comment by bnlawrence** [comment]
@davidhassell Do you know where in CMIP/CF these interval attributes are defined? Should we make a ticket for CF-Python to promote this information to the print statement?

**Comment by bnlawrence** [comment]
> I'm not aware of these attributes (interval_operation, interval_write) being used in CMIP6 - they're not mentioned in [CMIP6 Model Output Requirements: File Contents and Format, Data Structure and Metadata](https://docs.google.com/document/d/1os9rZ11U0ajY7F8FWtgU4B49KcB59aFlBVGfLC4ahXs)
> - nor standardized in CF.

Yet they appear in at least two sets of CMIP output from two different places ...  will ask Martin

**Comment by grenville** [comment]
I believe that we are OK with our current metadata
